name: CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checout@v2
    
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Run a multy-line script
      run: |
        echo Add other actions to bild,
        echo test, and deploy your project.
    
    
    
